build:
  version: "3.0"

accounts:
  message: "Welcome to Accounts related local APIs"
  contactDetails:
    name: "Wemeka"
    email: "abc@def.com"
  onCallSupport:
    -(555) 555-5555
    -(555) 555-1234


